### ISSUE TITLE
ColorMime doesn't generate pallete.

### ISSUE THREAD

**Issue by hauschild** [jtmarmon/ColorMime#3]
1 - I made the rectangle.
2 - Colormime asks for a URL
3 - I give the url, the theme number appears in a little box in the center-bottom of the screen.
4 - Little box goes away. Nothing happens.

**Comment by tyrale** [comment]
Same issue. Very annoying.

**Comment by dylane1** [comment]
A bit of info I pulled from the Console:

TypeError: undefined is not an object (evaluating 'random_palette["colors"]').
Plugin "ColorMime", line 456.
>> var palette_colour_list = random_palette["colors"]; <<

**Comment by jtmarmon** [comment]
should work now. let me know

**Comment by dylane1** [comment]
I'm still getting the same error with the updated alessndro_library.js

**Comment by jtmarmon** [comment]
hm weird, i might have fudged something let me take another look

**Comment by jtmarmon** [comment]
odd. I just doubled check that my files match exactly what's in the commit and it's working fine. what OS and sketch version are you on? and can anyone else confirm? @tyrale @hauschild

**Comment by dylane1** [comment]
I'm on Yosemite 10.10.2 (14C109), Sketch 3.2.2 (9983)

Maybe I didn't install correctly? I trashed the ColorMime directory from Plugins, then unzipped ColorMime-master into the Plugins directory. I even restarted Sketch, but still not working.

**Comment by jtmarmon** [comment]
ah you're right i just cleared it out and reinstalled with no luck. i could swear there was no difference... taking a second look now

**Comment by jtmarmon** [comment]
now it should be set @dylane1

**Comment by dylane1** [comment]
It works! Awesome!

**Comment by hauschild** [comment]
It works perfectly. Thank you!
